---
title: "Untitled"
output: html_document
date: "2025-03-20"
---

```{r}
library(MuMIn)
library(glmmTMB)
library(tidyverse)
library(broom) 
```

```{r data for modelling}

squirrels_all <- read_csv("all_arrays_proportional_presence_weekly_with_covariates.csv")
```

## 1. Models 

The "core model" is the best performing habiat model that will be used in 
subsequent models. 

How to do proper model syntax when there is different scales? 

```{r the core model(s)}

# null model 
core_h0 <- glmmTMB::glmmTMB(cbind(red_squirrel, absent_red_squirrel) ~ 1 +
                     (1|array), 
                     data = squirrels_all, 
                     family = "binomial")

# conifer
core_h1 <- glmmTMB::glmmTMB(cbind(red_squirrel, absent_red_squirrel) ~ 
                     scale(lc_coniferous_250) +
                     (1|array), 
                     data = squirrels_all, 
                     family = "binomial")

summary(core_h1)

# conifer + mixed
core_h2 <- glmmTMB::glmmTMB(cbind(red_squirrel, absent_red_squirrel) ~ 
                     scale(lc_coniferous_250) +
                     scale(lc_mixed_1000) +
                     (1|array), 
                     data = squirrels_all, 
                     family = "binomial")

summary(core_h2)

# conifer + mixed + broadleaf
core_h3 <- glmmTMB::glmmTMB(cbind(red_squirrel, absent_red_squirrel) ~ 
                     scale(lc_coniferous_250) +
                     scale(lc_mixed_1000) +
                     scale(lc_broadleaf_250) +
                     (1|array), 
                     data = squirrels_all, 
                     family = "binomial")

summary(core_h3)

# conifer + mixed + broadleaf + open veg
core_h4 <- glmmTMB::glmmTMB(cbind(red_squirrel, absent_red_squirrel) ~ 
                     scale(lc_coniferous_250) +
                     scale(lc_mixed_1000) +
                     scale(lc_broadleaf_250) +
                     scale(lc_grassland_750) +
                     scale(lc_shrub_1000) +
                     (1|array), 
                     data = squirrels_all, 
                     family = "binomial")

summary(core_h4)

```

Disturbance models 

```{r the disturbance model(s)}
dist_h0 <- glmmTMB::glmmTMB(cbind(red_squirrel, absent_red_squirrel) ~ 
                     top model  +
                     (1|array), 
                     data = squirrel, 
                     family = "binomial")

dist_h1 <- glmmTMB::glmmTMB(cbind(red_squirrel, absent_red_squirrel) ~ 
                     scale(seismic)  +
                     scale(linear) +
                     scale(roads) +
                     (1|array), 
                     data = squirrel, 
                     family = "binomial")


dist_h2 <- glmmTMB::glmmTMB(cbind(red_squirrel, absent_red_squirrel) ~ 
                     scale(harvest)  +
                     scale(wells) +
                     (1|array), 
                     data = squirrel, 
                     family = "binomial")


dist_h3 <- glmmTMB::glmmTMB(cbind(red_squirrel, absent_red_squirrel) ~ 
                     scale(osm_industrial)  +
                     (1|array), 
                     data = squirrel, 
                     family = "binomial")


dist_h4 <- glmmTMB::glmmTMB(cbind(red_squirrel, absent_red_squirrel) ~ 
                     core model +
                     scale(seismic)  +
                     scale(linear) +
                     scale(roads) +
                     scale(harvest)  +
                     scale(wells) +
                     scale(osm_industrial)  +
                     (1|array), 
                     data = squirrel, 
                     family = "binomial")


dist_h5 <- glmmTMB::glmmTMB(cbind(red_squirrel, absent_red_squirrel) ~ 
                     core model +
                     scale(seismic)  +
                     scale(linear) +
                     scale(roads) +
                     scale(harvest)  +
                     scale(wells) +
                     (1|array), 
                     data = squirrel, 
                     family = "binomial")

```


