---
title: "Untitled"
output: html_document
date: "2025-04-04"
---

names(data)

```{r}
comp_models <- purrr::map(unique(data_scaled$buffer_dist), ~{
  
  cat("\r\r Fitting models at scale:", .x, "meters      ")

  data_subset <- data_scaled %>%
    
    filter(buffer_dist == .x)
  
  
    c_null <- glmmTMB(squirrel ~ 
                        #lc_coniferous + 
                        #lc_mixedwood + 
                        #lc_broadleaf + 
                        #fire_0_15 + 

                        #pipe_trans + 
                        #seismic + 
                        #wells_inactive + 
                        #harvest_total +
                        #wells_active +
                        #osm_industrial +
                        #harvest_0_15
                        #roads +
                        
                        (1|array/site),
                      
                      data = data_subset, 
                      family = nbinom2, 
                      na.action = na.fail)
  
  
  c_null_core <- glmmTMB(squirrel ~ 
                        lc_coniferous + 
                        lc_mixedwood + 
                        lc_broadleaf + 
                        fire_0_15 + 

                        #pipe_trans + 
                        #seismic + 
                        #wells_inactive + 
                        #harvest_total +
                        #wells_active +
                        #osm_industrial +
                        #harvest_0_15
                        #roads +

                        (1|array/site),
                      
                      data = data_subset, 
                      family = nbinom2, 
                      na.action = na.fail)
  
  
  m_seis_wells <- glmmTMB(squirrel ~ 
                        lc_coniferous + 
                        lc_mixedwood + 
                        lc_broadleaf + 
                        fire_0_15 + 
                          
                        pipe_trans + 
                        seismic + 
                        wells_inactive + 
                        #harvest_total +
                        #wells_active +
                        #osm_industrial +
                        #harvest_0_15 +
                        #roads + 

                        (1|array/site),
                      
                      data = data_subset, 
                      family = nbinom2, 
                      na.action = na.fail)
  
  
  m_harvest <- glmmTMB(squirrel ~ 
                        lc_coniferous + 
                        lc_mixedwood + 
                        lc_broadleaf + 
                        fire_0_15 + 
                         
                        #pipe_trans + 
                        #seismic + 
                        #wells_inactive + 
                        #harvest_total +
                        #wells_active +
                        #osm_industrial +
                        harvest_0_15 +
                        #roads + + 

                        (1|array/site),
                      
                      data = data_subset, 
                      family = nbinom2, 
                      na.action = na.fail)
  
  m_harvest_seis <- glmmTMB(squirrel ~ 
                        lc_coniferous + 
                        lc_mixedwood + 
                        lc_broadleaf + 
                        fire_0_15 + 
                              
                        pipe_trans + 
                        seismic + 
                        wells_inactive + 
                        #harvest_total +
                        #wells_active +
                        #osm_industrial +
                        harvest_0_15 +
                        #roads + 

                        (1|array/site),
                      
                      data = data_subset, 
                      family = nbinom2, 
                      na.action = na.fail)
  
  
  m_active <- glmmTMB(squirrel ~ 
                        lc_coniferous + 
                        lc_mixedwood + 
                        lc_broadleaf + 
                        fire_0_15 + 
                        
                        #pipe_trans + 
                        #seismic + 
                        #wells_inactive + 
                        #harvest_total +
                        wells_active +
                        osm_industrial +
                        #harvest_0_15 +
                        #roads + 

                        (1|array/site),
                      
                      data = data_subset, 
                      family = nbinom2, 
                      na.action = na.fail)
  
  m_active_harvest <- glmmTMB(squirrel ~ 
                        lc_coniferous + 
                        lc_mixedwood + 
                        lc_broadleaf + 
                        fire_0_15 + 
                          
                        #pipe_trans + 
                        #seismic + 
                        #wells_inactive + 
                        #harvest_total +
                        wells_active +
                        osm_industrial +
                        harvest_0_15 +
                       # roads + 

                        (1|array/site),
                      
                      data = data_subset, 
                      family = nbinom2, 
                      na.action = na.fail)
  
  
  m_global <- glmmTMB(squirrel ~ 
                        lc_coniferous + 
                        lc_mixedwood + 
                        lc_broadleaf + 
                        fire_0_15 + 
                        
                        pipe_trans + 
                        seismic + 
                        wells_inactive + 
                        #harvest_total +
                        wells_active +
                        osm_industrial +
                        harvest_0_15 +
                        #roads + 

                        (1|array/site),
                      
                      data = data_subset, 
                      family = nbinom2, 
                      na.action = na.fail)
  
  MuMIn::model.sel(c_null, m_seis_wells, m_harvest, m_harvest_seis, m_active, m_active_harvest, 
                   m_global) %>%
  
    as.data.frame(.) %>%
    
    select(-`disp((Int))`) %>%
  
    rename_with(~ gsub("cond\\(|disp\\(|\\)|\\(", "", .)) %>%
    
    rename(intercept = `Int`) %>%
    
    mutate(model_name = rownames(.),
           buffer_dist = .x) %>%
    
    rename(delta_subset = delta)

  }
  ) %>%
  
  bind_rows(.) %>%
  
  mutate(delta = AICc - min(AICc)) %>%
  
  arrange(delta)

```

What are the top predictors and top spatial scale for our natural covariates?

```{r}
comp_predictors <- comp_models %>%
  
  select(1:which(names(.) == "df") - 1, -intercept) %>% 
  
  filter(row_number()==1) %>%
  
  select(where(~ !is.na(.))) %>%  # Remove columns with NA values

  colnames(.)
  
comp_buffer <- comp_predictors$buffer_dist[1]

comp_predictors
comp_buffer
```

